<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>dynamixel_hardware</name>
  <version>0.6.1</version>
  <description>[DEPRECATED] ros2_control hardware interface for ROBOTIS Dynamixel servo motors. Use dynamixel_hardware_interface instead: https://github.com/ROBOTIS-GIT/dynamixel_hardware_interface</description>
  <maintainer email="yutaka.kondo@youtalk.jp">Yutaka Kondo</maintainer>
  <license>Apache-2.0</license>

  <url type="repository">https://github.com/dynamixel-community/dynamixel_hardware</url>
  <url type="bugtracker">https://github.com/dynamixel-community/dynamixel_hardware/issues</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>lifecycle_msgs</depend>
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>dynamixel_workbench_toolbox</depend>

  <test_depend>ament_cmake_gmock</test_depend>
  <test_depend>ament_cmake_ros</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>builtin_interfaces</test_depend>
  <test_depend>controller_manager</test_depend>
  <test_depend>joint_state_broadcaster</test_depend>
  <test_depend>joint_trajectory_controller</test_depend>
  <test_depend>launch_ros</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>launch_testing_ros</test_depend>
  <test_depend>rclpy</test_depend>
  <test_depend>robot_state_publisher</test_depend>
  <test_depend>ros2_control_test_assets</test_depend>
  <test_depend>sensor_msgs</test_depend>
  <test_depend>trajectory_msgs</test_depend>
  <test_depend>xacro</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
