name: Build and Test

on:
  push:
    branches: [humble, jazzy, kilted, rolling, main, master]
  pull_request:
    branches: [humble, jazzy, kilted, rolling, main, master]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distro: humble
            os: ubuntu:jammy
          - ros_distro: jazzy
            os: ubuntu:noble
          - ros_distro: kilted
            os: ubuntu:noble
          - ros_distro: rolling
            os: ubuntu:noble

    name: Build and Test (${{ matrix.ros_distro }})
    container:
      image: ${{ matrix.os }}

    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          use-ros2-testing: true

      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: ${{ matrix.ros_distro }}
